django_32/article/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, re_path, path


from .views import (
    articles_view,
    article_detail_view,
    article_create_view,
    article_update_view,
    article_delete_view,
    search_article_view,
)

app_name = "article"

urlpatterns = [
    path('list/', articles_view, name='list'),
    path('search/', search_article_view, name='search'),
    path('detail/<int:article_id>/', article_detail_view, name='detail'),
    path('create/', article_create_view, name='add'),
    path('edit/', article_update_view, name='edit'),
    path('delete/', article_delete_view, name='delete'),
]

django_32/config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.urls import include, re_path, path


from .views import index_view

urlpatterns = [
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('article/', include('article.urls', namespace='article')),
    path('admin/', admin.site.urls),
    path('', index_view, name='home')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

django_32/configs/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.urls import include, re_path, path


from .views import index_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index_view, name='home')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

django_32/article/models.py
from django.db import models

# Create your models here.


class Article(models.Model):
    title = models.CharField(max_length=120)
    content = models.TextField()
    create_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

django_32/article/forms.py
from django import forms


from .models import Article


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'content']

    def clean(self):
        data = self.cleaned_data
        title = data.get('title')
        # This is mean this title is already created go throw the database to check
        # if this title already created or No
        qs = Article.objects.filter(title__icontains=title)
        # to kae it more clear stopped duplicated article 
        if qs.exists():
            self.add_error('title', f"{title} is already created. Try another article, please!")

        return data


class ArticleFormV1(forms.Form):
    title = forms.CharField()
    content = forms.CharField()
    # create_date = forms.DateTimeField()

    # def clean_title(self):
    #     cleaned_data = self.cleaned_data # dict
    #     print(cleaned_data, ' <<< cleaned data')
    #     title = cleaned_data.get('title')
    #     if title.lower().strip() == 'python':
    #         raise form.ValidationError('This title is taken')
    #     print(title, ' << title')
    #     return title

    # this method will clean all data fields

    def clean(self):
        cleaned_data = self.cleaned_data
        print('All fields', cleaned_data)
        title = cleaned_data.get('title')
        content = cleaned_data.get('content')
        if title.lower().strip() == 'python':
            self.add_error('title', 'This title is taken.')
            # raise form.ValidationError('This title is taken')
        if 'python' in content or 'python' in title:
            self.add_error('content', 'Python can not be in the content')
            raise form.ValidationError('The article is already taken')
        return cleaned_data

django_32/article/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404


from .models import Article
from .forms import ArticleFormV1, ArticleForm


def articles_view(request, *args, **kwargs):
    template_name = 'article_list.html'

    obj_qs = Article.objects.all()
    context = {
        'obj_list': obj_qs
    }
    return render(request, template_name, context)


def search_article_view(request):
    template_name = 'search.html'
    # print(dir(request))
    # print(request.GET)
    query_dict = request.GET  # This is dictionary

    try:
        query = int(query_dict.get('q'))
    except:
        query = None

    art_obj = None
    if query is not None:
        art_obj = Article.objects.get(id=query)

    context = {
        'object': art_obj,
    }
    return render(request, template_name, context)


def article_detail_view(request, article_id):
    template_name = 'article_detail.html'

    # if id is not None:
    #     art_obj = Article.objects.get(id=id)
    art = get_object_or_404(Article, pk=article_id)
    context = {
        'art': art,
    }
    return render(request, template_name, context)


@login_required
def article_create_view(request):
    template_name = 'create_article.html'
    form = ArticleForm(request.POST or None)
    context = {
        'form': form
    }

    if form.is_valid():
        data_obj = form.save()
        # This will clear the create form after new article created clear the page
        context['form'] = ArticleForm()

    return render(request, template_name, context)


# @login_required
# def article_create_view(request):
#     # print(request.POST)

#     template_name = 'create_article.html'
#     form = ArticleFormV1(request.POST or None)
#     print(dir(form))
#     context = {
#         'form': form
#     }
#     if request.method == 'POST':
#         form = ArticleFormV1(request.POST)
#         context['form'] = form
#         if form.is_valid():
#             title = form.cleaned_data.get('title')
#             content = form.cleaned_data.get('content')
#             print(title, content)
#             object_art = Article.objects.create(title=title, content=content)
#             context['object'] = object_art
#             context['create_date'] = True
   
#     return render(request, template_name, context)

# @login_required
# def article_create_view(request):
#     # print(request.POST)

#     template_name = 'create_article.html'
#     form = ArticleForm()
#     print(dir(form))
#     context = {
#         'form': form
#     }
#     if request.method == 'POST':
#         form = ArticleForm(request.POST)
#         context['form'] = form
#         if form.is_valid():
#             title = form.cleaned_data.get('title')
#             content = form.cleaned_data.get('content')
#             print(title, content)
#             object_art = Article.objects.create(title=title, content=content)
#             context['object'] = object_art
#             context['create_date'] = True
   
#     return render(request, template_name, context)


def article_update_view(request):
    template_name = 'edit_article.html'
    context = {

    }
    return render(request, template_name, context)


def article_delete_view(request):
    template_name = 'delete_article.html'
    context = {

    }
    return render(request, template_name, context)

django_32/article/templates/article_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container">

    <div class="row">

        <div class="col-8">
            <h3>{{art.title}}</h3>
            <p>{{art.content}}</p>
        </div>
        <div class="col-4">Picture</div>
    </div>

</div>
{% endblock content %}

django_32/article/templates/article_list.html
{% extends 'base.html' %}

{% block content %}
<main>
    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <form action="/article/list/" method="GET">
                    <input type="text" name="q"/>
                    <input type="submit" />
                </form>
            </div>
        </div>
    </section>
    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                {% for obj in obj_list %}
                <div class="col">
                    <div class="card shadow-sm">
                        <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
                        <div class="card-body">
                            <a href="{% url 'article:detail' obj.id %}"><h4>{{obj.title}}</h4></a>
                            <p class="card-text">{{obj.content}}</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                                    <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                                </div>
                                <small class="text-muted">9 mins</small>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</main>


{% endblock content %}

django_32/article/templates/create_article.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block content %}
<div class="container">

    <div class="row">

        <div class="col-8 mt-3">
            <br>
            <h3>Create Article</h3>
            <br><hr>

            <form method="POST" action="" class="form-control" >
                {% csrf_token %}
                
                {{form.as_p}}

                <button type="submit" class="button btn-primary mt-3">Create Article</button>
            </form>
        </div>
        <div class="col-4">Picture</div>

    </div>

</div>
{% endblock content %}

django_32/article/templates/search.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
    <h3>{{object.title}}</h3>
    <p>{{object.content}}</p>
{% endif %}

{% block content %}